### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by PeterDaveHello** [alberthier/git-webui#26]
It'll be great if the server can support https!

**Comment by Jiab77** [comment]
I took a look at the source code, on the web side, I didn't seen anything that would make your request impossible but on the Python side, I don't have the required skills to make the proper changes

**Comment by desyncr** [comment]
May be something like this: https://gist.github.com/dergachev/7028596

**Comment by alberthier** [comment]
I don't really see a use case for this.

You should not use git webui on the public internet, really not. It uses Python's integrated web server which is really not meant for that.

If you want to use webui on the internet, you should use nginx or Apache as frontal web server. These servers can handle the https without problem and redirect requests to webui.

Moreover enabling https on a lan means using self signed certificates. I cannot commit this certificate in the repository as it would make the secure layer pointless, so it would have to be generated at runtime. This means increased startup time. And than everyone accessing to your webui would be warned by their browser that the site is unsecure (because self-signed)

So, well, I think https is out of the scope of this little tool

**Comment by PeterDaveHello** [comment]
Hi @alberthier
 
Thanks for your explanation, I didn't understand your concern about the reason thy the Python's integrated web server is not for that, is that a security or performance issue?

It's not a problem for me to use Apache or nginx in front of it, just looking for the possibility if you'll like to have it integrated :)

**Comment by PeterDaveHello** [comment]
@desyncr thanks for the reference you provided, looks easy and useful!

**Comment by desyncr** [comment]
@alberthier More than reasonable.

**Comment by Jiab77** [comment]
@PeterDaveHello Not using Python's integrated web server is for security concerns
@desyncr Thanks for the reference ;)
@alberthier I agree with your reply, I was just ok with the idea to use git_webui over HTTPS instead HTTP, even on LAN (I don't care about the browser message because I know that I've generated myself my server certificate lol) But regarding to use git_webui from external networks, better use Apache or nginx as you said.

**Comment by alberthier** [comment]
Just to complete : the WebUiRequestHandler class in git-webui python script is a WSGI application.
Thus it should be possible to use Apache as web server and bind it with git-webui through mod_wsgi

I've never tested that, but it should be doable (maybe with some minor modifications)

**Comment by PeterDaveHello** [comment]
So maybe we can give it a try?

**Comment by Jiab77** [comment]
@PeterDaveHello Just fork and try ^^

**Comment by PeterDaveHello** [comment]
I'm not writing python yet, but could try in my sparse time :)

**Comment by Jiab77** [comment]
I understand, I've the same problem, I'd love to have my Python skills much better than they are... (I'm just able to read it and understand what it does but not enough to start a project from the ground)

**Comment by alberthier** [comment]
In fact it should almost work. It's more about setting up a proper Apache configuration.
So I'll close this issue

For WSGI related problems, I prefer that we open a new issue

**Comment by Jiab77** [comment]
@alberthier Ok, so I'll try on my side. How can I let you know if that works or not ?

**Comment by alberthier** [comment]
Just open a new issue with the problems you face.

Thanks
